import from http://qe-forge.org/gf/project/q-e/frs/

diff --git a/install/plugins_makefile b/install/plugins_makefile
--- a/install/plugins_makefile
+++ b/install/plugins_makefile
@@ -19,7 +19,7 @@ EXTLIBS=liblapack libblas libiotk
 ###########################################################
 ld1:  uncompress-ld1
 	if test -d ../atomic; then \
-	cd ../atomic; $(MAKE) all; cd ../bin; ln -fs ../atomic/src/ld1.x . ; fi
+	cd ../atomic; $(MAKE) all || exit 1; cd ../bin; ln -fs ../atomic/src/ld1.x . ; fi
 	touch make-ld1
 uncompress-ld1: touch-dummy
 	@(if test ! -s ../archive/$(LD1).tar.gz && test ! -d ../atomic ; then \
@@ -39,7 +39,7 @@ uncompress-ld1: touch-dummy
 ###########################################################
 xspectra:  uncompress-xspectra
 	if test -d ../XSpectra; then \
-	cd ../XSpectra; $(MAKE) all; cd ../bin; ln -fs ../XSpectra/src/xspectra.x . ; fi
+	cd ../XSpectra; $(MAKE) all || exit 1; cd ../bin; ln -fs ../XSpectra/src/xspectra.x . ; fi
 	touch make-xspectra
 uncompress-xspectra: touch-dummy
 	@(if test ! -s ../archive/$(XSPECTRA).tar.gz && test ! -d ../XSpectra ; then \
@@ -59,7 +59,7 @@ uncompress-xspectra: touch-dummy
 ###########################################################
 pwcond:  uncompress-pwcond
 	if test -d ../PWCOND; then \
-	cd ../PWCOND; $(MAKE) all; cd ../bin; ln -fs ../PWCOND/src/pwcond.x . ; fi
+	cd ../PWCOND; $(MAKE) all || exit 1; cd ../bin; ln -fs ../PWCOND/src/pwcond.x . ; fi
 	touch make-pwcond
 uncompress-pwcond: touch-dummy
 	@(if test ! -s ../archive/$(PWCOND).tar.gz && test ! -d ../PWCOND ; then \
@@ -80,7 +80,7 @@ uncompress-pwcond: touch-dummy
 ###########################################################
 neb:  uncompress-neb
 	if test -d ../NEB; then \
-	cd ../NEB; $(MAKE) all; cd ../bin; ln -fs ../NEB/src/neb.x . ; fi
+	cd ../NEB; $(MAKE) all || exit 1; cd ../bin; ln -fs ../NEB/src/neb.x . ; fi
 	touch make-neb
 uncompress-neb: touch-dummy
 	@(if test ! -s ../archive/$(NEB).tar.gz && test ! -d ../NEB ; then \
@@ -100,7 +100,7 @@ uncompress-neb: touch-dummy
 ###########################################################
 tddfpt:  uncompress-tddfpt
 	if test -d ../TDDFPT; then \
-	cd ../TDDFPT; $(MAKE) all; cd ../bin; ln -fs ../TDDFPT/src/turbo_lanczos.x . ; \
+	cd ../TDDFPT; $(MAKE) all || exit 1; cd ../bin; ln -fs ../TDDFPT/src/turbo_lanczos.x . ; \
 	ln -fs ../TDDFPT/tools/turbo_spectrum.x . ; fi
 	touch make-tddfpt
 uncompress-tddfpt: touch-dummy
@@ -121,7 +121,7 @@ uncompress-tddfpt: touch-dummy
 ###########################################################
 phonon:  uncompress-phonon
 	if test -d ../PHonon; then \
-	cd ../PHonon; $(MAKE) all; cd ../bin; \
+	cd ../PHonon; $(MAKE) all || exit 1; cd ../bin; \
 	ln -fs ../PHonon/PH/ph.x . ; \
 	ln -fs ../PHonon/PH/dynmat.x . ; \
 	ln -fs ../PHonon/PH/matdyn.x . ; \
@@ -149,15 +149,10 @@ uncompress-phonon: touch-dummy
 ##########################################################
 # GIPAW
 ###########################################################
-#gipaw:  uncompress-gipaw configure-gipaw
-gipaw:  download-gipaw configure-gipaw
+gipaw:  uncompress-gipaw configure-gipaw
 	if test -d ../GIPAW; then \
-	cd ../GIPAW; $(MAKE) all; cd ../bin; ln -fs ../GIPAW/bin/gipaw.x . ; fi
+	cd ../GIPAW; $(MAKE) all || exit 1; cd ../bin; ln -fs ../GIPAW/src/gipaw.x . ; fi
 	touch make-gipaw
-download-gipaw:
-	@echo "GIPAW 5 is not ready for distribution. Donwloading the development version."
-	@echo "This version is not bug free. Please, check if your results make sense."
-	svn checkout http://qeforge.qe-forge.org/svn/qe-gipaw/trunk ../GIPAW
 uncompress-gipaw: touch-dummy
 	@(if test ! -s ../archive/$(GIPAW).tar.gz && test ! -d ../GIPAW ; then \
 	wget -O ../archive/$(GIPAW).tar.gz $(GIPAW_URL) > /dev/null 2>&1; \
@@ -167,7 +162,7 @@ uncompress-gipaw: touch-dummy
 	echo "*** Unable to download qe-gipaw. Test whether curl or wget is installed and working," ; \
 	echo "*** if you have direct access to internet. If not, copy into archive/ the file" ; \
 	echo "*** $(GIPAW).tar.gz from $(GIPAW_URL)." ; \
-	exit 1 ; fi ; fi ; fi) 
+	exit 1 ; fi ; fi ; fi )
 	if test ! -d ../GIPAW; then \
 	(gzip -dc ../archive/$(GIPAW).tar.gz | (cd ../ ; tar -xvf -)) ; \
 	(cd ../ ; ln -s $(GIPAW) GIPAW) ; fi 
@@ -176,12 +171,14 @@ configure-gipaw: touch-dummy
 	cd ../GIPAW ; \
 	./configure --with-qe-source=${TOPDIR}
 	touch ./configure-gipaw
+
 ##########################################################
 # EPW
 ###########################################################
 epw: 
 	if test -d ../EPW; then \
-	cd ../EPW; $(MAKE) all; cd ../bin; ln -fs ../EPW/bin/epw.x . ; fi
+	cd ../EPW; $(MAKE) all || exit 1; cd ../bin; ln -fs ../EPW/bin/epw.x . ; fi
+	-(cd ../bin; ln -fs ../EPW/src/epw.x .)
 	touch make-epw
 
 ###########################################################
@@ -190,7 +187,7 @@ epw:
 
 w90: uncompress-w90 configure-w90
 	if test -d ../W90; then \
-	cd ../W90; $(MAKE) all; cd ../bin; ln -fs ../W90/wannier90.x . ; fi
+	cd ../W90; $(MAKE) all || exit 1; cd ../bin; ln -fs ../W90/wannier90.x . ; fi
 	-(cd ../bin; ln -fs ../W90/wannier90.x .)
 	touch make-w90
 uncompress-w90: touch-dummy
@@ -219,7 +216,7 @@ configure-w90: touch-dummy
 
 want: extlibs uncompress-want configure-want
 	if test -d ../WANT; then \
-	cd ../WANT; $(MAKE) all; fi
+	cd ../WANT; $(MAKE) all || exit 1; fi
 #	- ( cd ../bin ; ln -sf ../WANT/bin/* . ) 
 	touch ./make-want
 uncompress-want: touch-dummy
@@ -234,15 +231,15 @@ uncompress-want: touch-dummy
 	exit 1 ; fi ; fi ; fi) 
 	if test ! -d ../WANT; then \
 	(gzip -dc ../archive/$(WANT)-base.tar.gz | (cd ../ ; tar -xvf -)) ; \
-	(cd ../ ; ln -s $(WANT) WANT) ; fi 
+	(cd ../ ; ln -sf $(WANT) WANT) ; fi 
 	touch uncompress-want
 
 configure-want: touch-dummy
 	cd ../WANT ; \
-	./conf/configure \
+	./configure \
 	--with-external-iotk \
-	IOTK_LIBS="-L../../S3DE/iotk/src -liotk" \
-	IOTK_INCLUDE="$(MOD_FLAG)../../S3DE/iotk/src" \
+	IOTK_LIBS="-L../../../S3DE/iotk/src -liotk" \
+	IOTK_INCLUDE="$(MOD_FLAG)../../../S3DE/iotk/src" \
 	CC="$(CC)" \
 	F90="$(F90)" \
 	MPIF90="$(MPIF90)" \
@@ -268,7 +265,7 @@ configure-want: touch-dummy
 
 yambo: extlibs uncompress-yambo configure-yambo
 	if test -d ../YAMBO; then \
-	cd ../YAMBO; $(MAKE) all; fi
+	cd ../YAMBO; $(MAKE) all || exit 1; fi
 	touch ./make-yambo
 uncompress-yambo: touch-dummy
 	@(if test ! -s ../archive/$(YAMBO).tar.gz && test ! -d ../YAMBO ; then \
@@ -330,8 +327,8 @@ uncompress-plumed: touch-dummy
 patch-plumed: touch-dummy
 	if test -d ../PLUMED; then \
 	(cd ../PLUMED ; export plumedir="`pwd`" ; \
-	cp  patches/plumedpatch_qespresso_5.0.sh ../ ; \
-	cd ../ ; ./plumedpatch_qespresso_5.0.sh -patch) ; fi	
+	cp  patches/plumedpatch_qespresso_5.1.sh ../ ; \
+	cd ../ ; ./plumedpatch_qespresso_5.1.sh -patch) ; fi	
 	touch ./patch-plumed
 
 ##################################
@@ -388,7 +385,7 @@ configure-sax: touch-dummy
 # extlibs
 ###################################
 extlibs:
-	test -n "$(EXTLIBS)" && ( cd .. ; $(MAKE) $(MFLAGS) $(EXTLIBS) || exit 1) || :
+	test -n "$(EXTLIBS)" && ( cd .. ; $(MAKE) $(EXTLIBS) || exit 1) || :
 
 ##########################################################
 # GUI
@@ -396,18 +393,41 @@ extlibs:
 gui:  uncompress-gui
 	touch make-gui
 uncompress-gui: touch-dummy
-	@(if test ! -s ../archive/$(GUI).tgz && test ! -d ../GUI && test ! -d ../$(GUI); then \
-	wget -O ../archive/$(GUI).tgz $(GUI_URL) > /dev/null 2>&1; \
+	@(if test ! -s ../archive/$(GUI).tar.gz && test ! -d ../GUI && test ! -d ../$(GUI); then \
+	wget -O ../archive/$(GUI).tar.gz $(GUI_URL) > /dev/null 2>&1; \
 	if test "`echo $$?`" -ne "0" ; then \
-	curl -o ../archive/$(GUI).tgz $(GUI_URL) > /dev/null 2>&1; \
+	curl -o ../archive/$(GUI).tar.gz $(GUI_URL) > /dev/null 2>&1; \
 	if test "`echo $$?`" -ne "0" ; then \
 	echo "*** Unable to download pwGUI. Test whether curl or wget is installed and working," ; \
 	echo "*** if you have direct access to internet. If not, copy into archive/ the file" ; \
 	echo "*** $(GUI).tar.gz from $(GUI_URL)." ; \
 	exit 1 ; fi ; fi ; fi) 
 	if test ! -d ../GUI && test ! -d ../$(GUI); then \
-	(gzip -dc ../archive/$(GUI).tgz | (cd ../ ; tar -xvf -)) ; fi
+	(gzip -dc ../archive/$(GUI).tar.gz | (cd ../ ; tar -xvf -)) ; fi
 	touch uncompress-gui
+
+##########################################################
+# GPU
+###########################################################
+gpu:  uncompress-gpu
+	touch make-gpu
+uncompress-gpu: touch-dummy
+	@(if test ! -s ../archive/$(GPU).tar.gz && test ! -d ../GPU && test ! -d ../$(GPU); then \
+	wget -O ../archive/$(GPU).tar.gz $(GPU_URL) > /dev/null 2>&1; \
+	if test "`echo $$?`" -ne "0" ; then \
+	curl -o ../archive/$(GPU).tar.gz $(GPU_URL) > /dev/null 2>&1; \
+	if test "`echo $$?`" -ne "0" ; then \
+	echo "*** Unable to download QE-GPU. Test whether curl or wget is installed and working," ; \
+	echo "*** if you have direct access to internet. If not, copy into archive/ the file" ; \
+	echo "*** $(GPU).tar.gz from $(GPU_URL)." ; \
+	exit 1 ; fi ; fi ; fi) 
+	@ echo ""
+	@ echo " *****************************************************************************"
+	@ echo " * QE-GPU has been downloaded under ./archive Please follow the instructions *"
+	@ echo " *   reported here: http://qe-forge.org/gf/project/q-e-gpu/                  *" 
+	@ echo " *****************************************************************************"
+	@ echo ""
+	touch uncompress-gpu
 
 ###################################
 # cleaning
@@ -478,8 +498,7 @@ phonon_veryclean: phonon_clean
 # exe links to main bin dir are deleted by PHonon Makefile
 
 gipaw_clean:
-	if test -d ../GIPAW; then (cd ../GIPAW; \
-	$(MAKE) clean); fi
+	if test -d ../GIPAW; then (cd ../GIPAW; $(MAKE) clean); fi
 	rm -f ../bin/gipaw.x
 	rm -rf ./make-gipaw 
 
@@ -527,14 +546,14 @@ yambo_veryclean: yambo_clean
 plumed_clean:
 	if test -d ../PLUMED; then (cd ../PLUMED; \
 	export plumedir="`pwd`" ; \
-	cd ../ ; ./plumedpatch_qespresso_5.0.sh -revert); fi
+	cd ../ ; ./plumedpatch_qespresso_5.1.sh -revert); fi
 	cd ../PW ; $(MAKE) clean; cd ../CPV ; $(MAKE) clean
 	rm -rf ./make-plumed ./patch-plumed
 
 plumed_veryclean: plumed_clean
 	if test -d ../PLUMED; then (rm -R -f ../PLUMED); fi
 	if test -d ../$(PLUMED); then (rm -R -f ../$(PLUMED)); fi
-	rm -rf ./uncompress-plumed ../plumedpatch_qespresso_5.0.sh
+	rm -rf ./uncompress-plumed ../plumedpatch_qespresso_5.1.sh
 
 sax_clean:
 	if test -d ../SaX; then (cd ../SaX; \
@@ -552,12 +571,18 @@ gui_clean:
 gui_veryclean: gui_clean
 # dir is not deleted for compatibility with the repository
 
+gpu_clean:
+	rm -f ./make-gpu 
+
+gpu_veryclean: gpu_clean
+# dir is not deleted for compatibility with the repository
+
 ##########################################################
 # general cleaning
 ##########################################################
 clean: w90_clean want_clean yambo_clean plumed_clean epw_clean \
 	gui_clean phonon_clean tddfpt_clean xspectra_clean neb_clean pwcond_clean \
-	ld1_clean gipaw_clean
+	ld1_clean gipaw_clean gpu_clean 
 veryclean: w90_veryclean want_veryclean yambo_veryclean plumed_veryclean epw_veryclean \
 	gui_veryclean phonon_veryclean tddfpt_veryclean xspectra_veryclean neb_veryclean \
-	pwcond_veryclean ld1_veryclean gipaw_veryclean
+	pwcond_veryclean ld1_veryclean gipaw_veryclean gpu_veryclean 
